In [1]:
import pandas as pd #load pandas

In [2]:
#Load dataset
play_data = pd.read_json('data/databoi_data_Set.json')

In [6]:
#inspect the types of data you have
play_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 385288 entries, 0 to 99999
Data columns (total 39 columns):
age_restriction            385288 non-null int64
android_version            385288 non-null object
app_name                   385288 non-null object
bug_fixes                  385288 non-null object
category                   385288 non-null object
current_version            385288 non-null object
description                385288 non-null object
developer_name             385288 non-null object
developer_website          385288 non-null object
five_stars                 385288 non-null int64
five_stars_d               385288 non-null int64
four_stars                 385288 non-null int64
four_stars_d               385288 non-null int64
id                         385288 non-null int64
in_app_purchases           385288 non-null object
installs                   385288 non-null object
installs_high              385288 non-null int64
installs_low               385288 non-null int64
interactive_elements       385288 non-null object
is_editors_choice          385288 non-null int64
last_updated               385288 non-null object
link                       385288 non-null object
logo_url                   385288 non-null object
one_star                   385288 non-null int64
one_star_d                 385288 non-null int64
other_apps_by_developer    385288 non-null object
parental_guide             385288 non-null object
permissions                385288 non-null object
price                      385288 non-null float64
price_currency             385288 non-null object
rating                     385288 non-null float64
rating_count               385288 non-null int64
record_time                385288 non-null datetime64[ns]
screenshots                385288 non-null object
three_stars                385288 non-null int64
three_stars_d              385288 non-null int64
two_stars                  385288 non-null int64
two_stars_d                385288 non-null int64
videos                     385288 non-null object
dtypes: datetime64[ns](1), float64(2), int64(16), object(20)
memory usage: 117.6+ MB

In [4]:
#Statistical description of data
play_data.describe().round(2)

,age_restriction,five_stars,five_stars_d,four_stars,four_stars_d,id,installs_high,installs_low,is_editors_choice,one_star,one_star_d,price,rating,rating_count,three_stars,three_stars_d,two_stars,two_stars_d
count,385288.00,385288.00,385288.00,385288.00,385288.00,385288.00,3.852880e+05,3.852880e+05,385288.00,385288.00,385288.00,385288.00,385288.00,385288.00,385288.00,385288.00,385288.00,385288.00
mean,0.50,7468.71,90.72,1646.42,19.19,194029.50,1.853763e+06,4.627855e+05,0.00,782.58,21.86,0.28,3.90,10952.31,743.94,11.69,310.66,6.32
std,2.64,217558.87,27.10,46995.69,19.90,111223.21,4.918482e+07,1.065746e+07,0.06,26508.46,28.32,3.10,1.13,317222.36,22450.38,15.28,9664.17,11.53
min,0.00,0.00,0.00,0.00,0.00,1386.00,-1.000000e+00,-1.000000e+00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.00,7.00,100.00,1.00,4.00,97707.75,5.000000e+03,1.000000e+03,0.00,1.00,2.00,0.00,3.72,11.00,0.00,0.00,0.00,0.00
50%,0.00,45.00,100.00,8.00,15.00,194029.50,5.000000e+04,1.000000e+04,0.00,7.00,11.00,0.00,4.21,75.00,5.00,8.00,2.00,3.00
75%,0.00,387.00,100.00,83.00,27.00,290351.25,1.000000e+05,5.000000e+04,0.00,62.00,28.00,0.00,4.54,637.00,47.00,16.00,22.00,8.00
max,18.00,45268388.00,100.00,11536306.00,100.00,386673.00,5.000000e+09,1.000000e+09,1.00,9066508.00,100.00,399.99,5.00,75322743.00,6737929.00,100.00,3216770.00,100.00

In [5]:
#Eyeball the data
play_data.head()

,age_restriction,android_version,app_name,bug_fixes,category,current_version,description,developer_name,developer_website,five_stars,...,price_currency,rating,rating_count,record_time,screenshots,three_stars,three_stars_d,two_stars,two_stars_d,videos
0,0,Varies with device,Wear LCD Ghost Remove,Added Android Wear 2.0 watches support,Tools,Varies with device,This app may help you remove LCD ghosts from y...,Entera Studio,https://www.google.com/url?q=http://entera.pl&...,6,...,USD,4.42857,7,2018-03-15 12:18:43,https://lh3.googleusercontent.com/320JbNU9Spab...,0,0,0,0,
1,0,4.0.3,Where is my Train : Indian Railway & PNR Status,"* Seat Availability Improved, * You can filter...",Travel & Local,5.4.7,"""Where is my Train"" is a unique train app that...",? Sigmoid Labs,https://www.google.com/url?q=https://whereismy...,204944,...,USD,4.65594,274402,2018-03-15 12:18:44,https://lh3.googleusercontent.com/HRwhUIxYI0_f...,11075,5,1928,0,
10,0,Varies with device,Weather Belgium XL PRO,bug fix in the weather sharing feature,Weather,Varies with device,This is simply the best weather app for your r...,Exovoid Sàrl,https://www.google.com/url?q=http://www.exovoi...,2382,...,USD,4.48578,3868,2018-03-15 12:18:50,https://lh5.ggpht.com/Ir__p9ynmkWsyuR8QZCgSTu6...,162,6,52,2,
100,0,Varies with device,Wake Up Well,Improve update of complication.,Health & Fitness,Varies with device,Transform your Android Wear watch into a smart...,AppDevs,N/A,91,...,USD,3.74872,195,2018-03-15 12:19:40,https://lh3.googleusercontent.com/ykFa_YQ9nztL...,20,21,15,16,
1000,0,4.4,Todoist: To-do lists for task management & err...,"New:, • Improved Quick add performance., • You...",Productivity,12.6,Life can feel overwhelming. But it doesn’t hav...,Doist,https://www.google.com/url?q=http://todoist.co...,95155,...,USD,4.46724,147982,2018-03-15 12:28:58,https://lh3.googleusercontent.com/OQNZcANY8YLT...,7221,7,2836,2,https://www.youtube.com/embed/VJo1pPRGUEg?ps=p...

## Summery Descriptive Stats<br>
Pandas have most basic calcuations as methods...follow on and see.

In [7]:
#Sum for each column
play_data[['two_stars','one_star']].sum()

two_stars    119693020
one_star     301518252
dtype: int64

In [8]:
#Get the the mean for each column
play_data[['two_stars','one_star']].mean(skipna=True)

two_stars    310.658572
one_star     782.578881
dtype: float64

In [9]:
#Get the the mean across the columns
play_data[['two_stars','one_star']].mean(axis=1, skipna=True)

0             0.5
1          2634.5
10           65.5
100          22.5
1000       3604.5
10000         1.5
100000        1.0
100001       74.0
100002       18.0
100003        3.5
100004     1516.5
100005        5.0
100006        0.5
100007        0.0
100008       20.5
100009       13.5
10001         0.0
100010       52.5
100011        0.5
100012        5.5
100013       49.5
100014        6.5
100015        0.0
100016       17.0
100017     2421.0
100018       26.0
100019        8.0
10002         0.0
100020        0.0
100021        0.0
           ...
99972        26.0
99973         1.5
99974        51.5
99975        12.0
99976       119.0
99977      3771.0
99978         0.5
99979       137.0
9998          1.0
99980     24942.5
99981         0.0
99982        14.0
99983      1913.0
99984         2.5
99985         5.0
99986       498.5
99987       383.5
99988         9.0
99989        22.5
9999          0.0
99990        36.5
99991       601.5
99992         1.0
99993       455.0
99994         8.5
99995         0.5
99996        22.5
99997         0.0
99998        30.0
99999         0.0
Length: 385288, dtype: float64

In [10]:
#Gives the row label for the lowest value in the series
play_data['one_star'].idxmin()

100007

In [11]:
#Gives the row label for the highest value in the series
play_data['one_star'].idxmax()

180017

In [12]:
#Gives a series of the cummulative values of the dataframe
play_data['one_star'].cumsum()

0                 1
1              3342
10             3421
100            3451
1000           7824
10000          7825
100000         7827
100001         7928
100002         7959
100003         7964
100004         9999
100005        10004
100006        10005
100007        10005
100008        10038
100009        10050
10001         10050
100010        10112
100011        10112
100012        10120
100013        10203
100014        10212
100015        10212
100016        10237
100017        14234
100018        14279
100019        14292
10002         14292
100020        14292
100021        14292
            ...
99972     301475717
99973     301475719
99974     301475785
99975     301475803
99976     301475962
99977     301481566
99978     301481567
99979     301481768
9998      301481770
99980     301512519
99981     301512519
99982     301512541
99983     301515313
99984     301515315
99985     301515324
99986     301516025
99987     301516517
99988     301516530
99989     301516560
9999      301516560
99990     301516611
99991     301517397
99992     301517398
99993     301518155
99994     301518170
99995     301518171
99996     301518204
99997     301518204
99998     301518252
99999     301518252
Name: one_star, Length: 385288, dtype: int64